# Generated by Django 4.2.3 on 2023-10-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100)),
                ('Cprincipal', models.CharField(max_length=100)),
                ('Clocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('Tage', models.IntegerField()),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='app.college')),
            ],
        ),
    ]
