# Generated by Django 4.2.3 on 2023-10-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('Tage', models.IntegerField()),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='app.college')),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
